FROM postgres:17.2-alpine

ENV POSTGRES_DB=db \
   POSTGRES_USER=usr \
   POSTGRES_PASSWORD=pwd

#COPY 01-CreateScheme.sql /docker-entrypoint-initdb.d/
#COPY InsertData.sql /docker-entrypoint-initdb.d/
COPY *.sql /docker-entrypoint-initdb.d/