name: CI devops 2025

on:
  push:
    branches:
      - tp-docker
      - master
  pull_request:

jobs:
  # JOB 1 : Test et Analyse Qualité (avec optimisation Cache)
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # Cache Maven pour ne pas retélécharger les JAR à chaque fois
          cache: 'maven'

      - name: Build and test with Maven
        # Utilisation de la clé d'organisation elgr3 validée précédemment
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=elgr3 -Dsonar.organization=elgr3 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./simpleapi/simpleapi/pom.xml

  # JOB 2 : Build et Push Backend (Parallèle)
  build-push-backend:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./simpleapi/simpleapi
          # Tracabilité :  Double Tag (latest + SHA du commit pour la traçabilité)
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/tp-docker' || github.ref == 'refs/heads/master' }}

  # JOB 3 : Build et Push Database (Parallèle)
  build-push-database:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push Database
        uses: docker/build-push-action@v6
        with:
          context: ./postgres
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/tp-docker' || github.ref == 'refs/heads/master' }}

  # JOB 4 : Build et Push HTTPD (Parallèle)
  build-push-httpd:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push HTTPD
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/tp-docker' || github.ref == 'refs/heads/master' }}